name: Pull Request Labeler
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label_my_pr_job:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      id: CheckOut
      uses: actions/checkout@v2
    - name: Display PR title
      id: myLabeler
      uses: Gerai2963/Label-by-pr-title@v1.5
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        config: '.github/pr_label_config.yml'
    - name: Output Labels
      run: echo "Display my labels ${{ steps.myLabeler.outputs.Labels}}"
    outputs:
      MyLabels: ${{steps.myLabeler.outputs.Labels}}
  required_label:
    needs: label_my_pr_job
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: ${{needs.label_my_pr_job.outputs.MyLabels}}
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "do-not-merge"


