on: [pull_request]

jobs:
  label_my_pr_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Display PR title
      uses: Gerai2963/Label-by-pr-title@v1.3
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        config: '.github/pr_label_config.yml'


