name: Playwright tests
on: 
  pull_request:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
      - uses: sohill-patel/playwright-playground@main
      - name: Install operating system dependencies
        run: npm install
      - name: Run your tests
        run: npm test